site_name: osCloud Services Documentation
site_author: 'osCloud Engineering Team'
site_url: 'https://docs.oscloud.io'
copyright: 'Copyright &copy; 2018 Omnificent Systems Inc. All Rights Reserved.'
nav:
    - Home: 'index.md'
    - Peering:
        - 'Peering Policy': 'Peering/Peering Policy.md'
    - Routing:
        - 'BGP Communities': 'Routing/BGP Community Structure.md'
    - Architecture:
        - 'osConnect': 
            - 'Example Design 1': 'Architecture/osConnect/sample-option1.md'
            - 'Example Design 2': 'Architecture/osConnect/sample-option2.md'
# Theme Configuration
theme:
  name: 'material'
  palette:
    primary: 'white'
    accent: 'blue'
  font:
    text: 'Raleway'
    code: 'Fira Mono'
  logo:
    icon: 'folder'
  favicon: 'assets/favicon.ico'
  feature:
    tabs: true
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
# Social Links
extra:
  social:
    - type: 'globe'
      link: 'https://www.oscloud.io'
    - type: 'envelope'
      link: 'mailto:peering@oscloud.io'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/omnificent-systems-inc-/'
    - type: 'connectdevelop'
      link: 'https://as395077.peeringdb.com'
